### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by relrod** [AllStarLink/ASL-Supermon#1]
There are [two](https://github.com/AllStarLink/ASL-Supermon/blob/develop/var/www/html/supermon/LICENSE) license [files](https://github.com/AllStarLink/ASL-Supermon/blob/develop/LICENSE) that indicate this project is GPLv3, but a [bunch](https://github.com/AllStarLink/ASL-Supermon/blob/develop/var/www/html/supermon/ast_reload.php#L6) of [file headers](https://github.com/AllStarLink/ASL-Supermon/blob/develop/var/www/html/supermon/astlog.php#L8) that [revoke](https://github.com/AllStarLink/ASL-Supermon/blob/develop/var/www/html/supermon/connectlog.php#L6) [commercial](https://github.com/AllStarLink/ASL-Supermon/blob/develop/var/www/html/supermon/dtmf.php#L7) [use](https://github.com/AllStarLink/ASL-Supermon/blob/develop/var/www/html/supermon/reboot.php#L6).

Can someone please clarify the license for this project? "GPLv3 except for a bunch of files intrinsic to the project that are non-FOSS" seems odd at best, sad at worst.

Thanks

**Comment by N0NB** [comment]
A non-trivial number of files contain the `For ham radio use only, NOT for comercial use!` text, which is in direct contradiction to the GPL of either version 2 or 3.  Unfortunately, this seems to be a licensing trope that has been around amateur radio for many years.  This clause would also make the software in question "NON-FREE" per the Debian Free Software Guidelines (DFSG).

Other files carry no copyright/license notice.  In some cases they are shell scripts that are trivial and could probably be assumed to be licensed under the main LICENSE document.

Straightening this mess out will not be easy though the easiest path is to contact Paul Aidukas, KN2R (the files I have seen with the text in question show him as the author) and see if he'll agree to having that text removed and replaced by the GPL boilerplate.  If he will not agree or cannot be contacted, then either a document should be created listing the files covered by the GPL and those not or a rewrite be done of the files in question that then licensed under the GPL.

IANAL, but I've been around Free Software development for some time and have picked up a few pointers along the way.
